<?php
	$con=mysqli_connect("localhost","root","","lpexceldb");
	if (mysqli_connect_errno()){						// Check connection
	  	echo "Failed to connect to MySQL: " .mysqli_connect_error();
	  }
	$csvfile = array();							//Array to hold Row data
	$colHead = array();						//Array to hold Column Name from DB
	$countRes = mysqli_query($con,"select count(*) from products");
	$cnt = mysqli_fetch_array($countRes);
	$count = $cnt[0];
	$lp = 0;
	
	$colsQ = "SELECT `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA`='lpexceldb' AND `TABLE_NAME`='products'";
	$columns = mysqli_query($con,$colsQ);
	while($col = mysqli_fetch_array($columns) ){
		$colHead[]=$col[0];
	}
	if(($_FILES["file"]["type"] == "text/csv")||($_FILES["file"]["type"] == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")){
		if($_FILES["file"]["type"] == "text/csv"){
			$file = fopen($_FILES["file"]["tmp_name"],"r");
			while(! feof($file)){
				$csv = fgetcsv($file, 10000, ","); 		// get row
				$csvfile[]=$csv;				//put row in array
				$rowSize = sizeof($csvfile[0]);
				$columns = "";					//insert array of row to db
				$values ="";
				for($r=0;$r<$rowSize;$r++){			//creating string of values
					$coldata = $csvfile[0][$r];
					if($colHead[$r] == 'id'){
										// generated by database
					}else if($colHead[$r] == "prod_id"){
						$prodid = rand($cnt[0],9999999);
						$columns = $columns."`".$colHead[$r]."`,";
						$values = $values.",'"."GHPRODID_".$prodid."'";						
					}else{
						if($coldata != "" && $coldata != "NULL" && $coldata != NULL){
							if(is_numeric($coldata)){
								$values = $values.",".$coldata;
							}
							else if(!is_numeric($coldata)){
								$coldata = "'".$coldata."'"; // text in quotes
								$values = $values.",".$coldata;
							}
							$columns = $columns."`".$colHead[$r]."`,";
						}
					}
					
				}
				$values = substr($values,1);
				$columns = rtrim($columns,',');
				
				if((isset($columns)&&isset($values))&&($columns !="" && $values !="")){
					$query = "INSERT INTO `products` (".$columns.") 
					 values(".$values.")";
				}
				
				unset($csvfile);				//clear array of row
				
				if(!mysqli_query($con,$query)){
					echo "Error: ".mysqli_error($con);
				}else{
				$lp = $lp +1;
				echo "<br><b>".$lp."</b><br>".$query;
					/*echo "<script type=\"text/javascript\">
						alert(\"".$_FILES["file"]["name"]." File has been successfully Imported.\");
						window.location = \"lpexcel.php\"
					</script>";
					*/
				}
				//echo $query."<br><br>";
			}
			fclose($file);
			
	
		}
		if($_FILES["file"]["type"] == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"){
			echo " This file type will be supported soon";
			
		}
	}
?>
